export const markerEvents = [
  'animation_changed',
  'click',
  'clickable_changed',
  'contextmenu',
  'cursor_changed',
  'dblclick',
  'drag',
  'dragend',
  'draggable_changed',
  'dragstart',
  'flat_changed',
  'icon_changed',
  'mousedown',
  'mouseout',
  'mouseover',
  'mouseup',
  'position_changed',
  'shape_changed',
  'title_changed',
  'visible_changed',
  'zindex_changed',
  'rightclick',
];

export const infoWindowEvents = [
  'closeclick',
  'content_changed',
  'domready',
  'position_changed',
  'visible',
  'zindex_changed',
];
