export const mapEvents = [
  'bounds_changed',
  'center_changed',
  'click',
  'contextmenu',
  'dblclick',
  'drag',
  'dragend',
  'dragstart',
  'heading_changed',
  'idle',
  'isfractionalzoomenabled_changed',
  'mapcapabilities_changed',
  'maptypeid_changed',
  'mousemove',
  'mouseout',
  'mouseover',
  'projection_changed',
  'renderingtype_changed',
  'tilesloaded',
  'tilt_changed',
  'zoom_changed',
  'rightclick',
]

export const markerEvents = [
  'animation_changed',
  'click',
  'clickable_changed',
  'contextmenu',
  'cursor_changed',
  'dblclick',
  'drag',
  'dragend',
  'draggable_changed',
  'dragstart',
  'flat_changed',
  'icon_changed',
  'mousedown',
  'mouseout',
  'mouseover',
  'mouseup',
  'position_changed',
  'shape_changed',
  'title_changed',
  'visible_changed',
  'zindex_changed',
  'rightclick',
] as const

export type MarkerEvent = typeof markerEvents

export const infoWindowEvents = [
  'closeclick',
  'content_changed',
  'domready',
  'position_changed',
  'visible',
  'zindex_changed',
]
